apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ca-injector
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhekNDQWxPZ0F3SUJBZ0lVSVFEdFlkVnlZeklhcHZObmRScllvakIrU1RVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TWpFd01qTXhPVEE0TXpWYUZ3MHlNakV4Ck1qSXhPVEE0TXpWYU1FVXhDekFKQmdOVkJBWVRBa0ZWTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzcraTE4Wjc2NHFzQTFhYmpZdlhiTzVHU20reGZtYUx0ak5WK21FZitaCk03RzZjd2tHYkxFUlZDZVg5c3Y2ZUNFUkNYOGxvZVFQLzhXekhzVTJucGVLZU9HaGZEc0lMTWV4VVM3TklSc2cKS216VGR2MDVyZndYQWl1VW1Sam9iWWYxUkl2ZVBWMFJPMXh2NUY3aDZlY1VEV3loVW10cE8rbStUNVNTenFSWQpBWGFrWnBtaHZ4OFFsS0hyUzY2dW1EWFdtMHNSOWNZUm5BeE82U1V0SW9MUWZZam1GTlRwTXk2c3ozanhlemZDCko5WWZzRWlBUzJ0SDg4UTcyK2t1Y3pRRGZ6MU8zWElLTUU2OEV4ZVdEbVJscWV0ZU9QU3lHQjcyTG10QmpPZ00KektTZlBpRDJ3enFPZkRCQXlSaE56ZzhyTkFiOWJUTWp6S3lOT3RsSzhIQUZBZ01CQUFHalV6QlJNQjBHQTFVZApEZ1FXQkJUOEk3WkhMSWxIVE42RHZWTUNmcDFNQVZVaXFEQWZCZ05WSFNNRUdEQVdnQlQ4STdaSExJbEhUTjZECnZWTUNmcDFNQVZVaXFEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0wKRFpYVDgybHBjSE13VzdseWRIbjd5eC9oKytraVlBVVprcE92bTZoSTJvZVFvL09wZGdNSklBMEtaLytjYnlzZQphdGFhMk82cm9MbVhkdjBDbkFzdFZhcmxnZ2V3RlBudVZGYUJIajRpZW1INGp2RGhwSXZKQ0Y2MnhyU2RScE9rCmpyZVZGbWI5eXZwRkhUVUluVVVjUUQvWUNTei9kU0JKdjZaRUs0UnBBd1BzQ3djRXlhMmlqQWZjMUpwZmJJejcKbHdBckNZcDdkazI0aXFxdkh5aXNFQTc0S3pFSVhnZWM0VjQ0M2FFblZUMFlGclBjQ3JLVHlXTzJCMWNkZzJpRgpIOWNYUUUyTlIzWmdBZEVXdU41RTlNNURBNE51Zk9kRW4xMDZpRVZsb0xObEdKMUpBOEl5UnduNGhSbFg5UllhCjVxZ2lFMFlVTENYTDl4OVNRRE5OCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: ca-injector
      namespace: example
      path: /mutate
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: ca-injector.botland.svc
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-public
      - kube-node-lease
  objectSelector:
    matchExpressions:
    - key: app
      operator: NotIn
      values:
      - ca-injector
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
