apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kac
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get