apiVersion: v1
kind: ConfigMap
metadata:
  name: kac-config
  namespace: example
data:
  config.yaml: |
    annotations:
      inject: ptonini.github.io/inject-ca
      injected: ptonini.github.io/ca-injected
    configMapName: kac
    rootCA:
      baltimore:
        type: url
        source: https://www.digicert.com/CACerts/BaltimoreCyberTrustRoot.crt.pem