apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  annotations:
    "ptonini.github.io/inject-ca": baltimore
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx